import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavbarComponent } from "@/Components";
import { FooterComponent } from "@/Components";
import { Toaster } from 'react-hot-toast';
import ContextCartProvider from "@/contexts/contextCart";
import ProviderRedux from "@/Components/ProviderRedux";
import { AuthSessionProvider } from "@/contexts/AuthProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "VeloraTech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthSessionProvider>
          <ProviderRedux>
            <ContextCartProvider>
              <NavbarComponent />
              <Toaster position="top-center" />
              {children}
              <FooterComponent />
            </ContextCartProvider>
          </ProviderRedux>
        </AuthSessionProvider>


      </body>
    </html>
  );
}
